name: Alerta para Discord

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  enviar_alerta:
    runs-on: ubuntu-latest

    steps:
    - name: Enviar alerta para Discord
      run: |
        curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\": \"🚀 Novo push ou PR mergeado no repositório!\"}" \
          ${{ secrets.DISCORD_WEBHOOK }}